### ISSUE TITLE
ImportError: cannot import name 'send_password_reset_email' from 'app.email' 

### ISSUE THREAD

**Issue by vangourd** [dnova02/microblog#3]
I'm experiencing an import error when using the instructions provided in your readme to run the app. 

```
(.venv) PS C:\Users\brian\dev\microblog> flask run
Usage: flask run [OPTIONS]      
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\brian\dev\microblog\.venv\Lib\site-packages\flask\cli.py", line 218, in locate_app    __import__(module_name)
  File "C:\Users\brian\Dev\microblog\app\__init__.py", line 20, in <module>
    from app import routes, models, errors
  File "C:\Users\brian\Dev\microblog\app\routes.py", line 19, in <module>
    from app.email import send_password_reset_email
ImportError: cannot import name 'send_password_reset_email' from 'app.email' (C:\Users\brian\Dev\microblog\app\email.py)
```

**Comment by vangourd** [comment]
I'm not seeing a `send_password_reset_email` in [email.py](https://github.com/dnova02/microblog/blob/main/app/email.py)
